### ISSUE TITLE
Wordpress posts with quotes in title causes malformed markdown

### ISSUE THREAD

**Issue by andrewboni** [hexojs/hexo-migrator-wordpress#2]
The migration plugin seems to work well, except there is a bug when importing posts that use quotes in the titles.

For instance, look at this Wordpress post title:
```
Alexander - “Truth” Music Video
```
...will cause issues when importing, due to the quotes in the title. These should be escaped upon import.

Another example:
```
The Cataracs feat. Dev - "Bass Down Low" (Proper Villians Remix)
```
...leads to yaml front-matter that looks like:

```yaml
id: 3574
categories:
  - Electro Hop
tags:
  - Dev
  - Far East Movement
  - The Cataracs
---
title: "The Cataracs feat. Dev - "Bass Down Low" (Proper Villians Remix)"
date: 2011-01-10 02:14:22
tags:
---
```

...which is incorrect. Any way we can escape the post titles upon import? Thanks!
